name: Build Flatpak Bundle
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: true
        default: "7.6.45-Release.5032501"
  pull_request:

jobs:
  build-bundle:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        arch: [x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Flatpak
        run: |
          sudo apt-get -q update
          sudo apt-get -q install -y flatpak flatpak-builder
          sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install --noninteractive --arch=${{ matrix.arch }} org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08
          git config --global protocol.file.allow always # https://github.com/flatpak/flatpak-builder/issues/495
      - name: Build
        run: |
          flatpak-builder --arch=${{ matrix.arch }} --install --user --delete-build-dirs --force-clean build com.alibabainc.DingTalk.yaml
          flatpak build-bundle ~/.local/share/flatpak/repo/ com.alibabainc.DingTalk-${{ matrix.arch }}.flatpak com.alibabainc.DingTalk
      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date -u '+%y%m%d%H%M')" >> $GITHUB_OUTPUT
      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-bundle-${{ matrix.arch }}
          path: com.alibabainc.DingTalk-${{ matrix.arch }}.flatpak
      - name: Upload to Release
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.version }}_${{ steps.date.outputs.CURRENT_DATE }}
          tag_name: ${{ github.event.inputs.version }}_${{ steps.date.outputs.CURRENT_DATE }}
          files: com.alibabainc.DingTalk-*.flatpak
          body: |
            install via:
            ```
            flatpak install com.alibabainc.DingTalk-<arch>.flatpak
            ```
